# Test build the March tutorials. Author: Isha Dijcks
# Adapted from 'Test build the MoveIt! tutorials'. Original Author: Dave Coleman

sudo: required
dist: xenial
language: ruby
rvm:
  - 2.4
python:
  - "2.7"
cache: ccache
compiler: gcc

before_install: # Use this to prepare the system to install prerequisites or dependencies
  - export ROS_DISTRO=kinetic
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - sudo -E sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-wstool python-catkin-tools

  # Setup rosdep
  - sudo rosdep init
  - rosdep update

  # Install htmlproofer
  - gem update --system
  - gem --version
  - gem install html-proofer

  # Install ROS's version of sphinx
  - sudo apt-get -qq install ros-kinetic-rosdoc-lite
  - source /opt/ros/kinetic/setup.bash

before_script:
  - cd ~/catkin_ws/src
  - wstool init
  - if [[ -f $ROSINSTALL_FILE ]] ; then wstool merge $ROSINSTALL_FILE ; fi
  - wstool up

script:
  # Test build with non-ROS wrapped Sphinx command to allow warnings and errors to be caught
  - sphinx-build -W -b html . native_build
  # Test build with ROS-version of Sphinx command so that it is generated same as ros.org
  - rosdoc_lite -o build .
  # Run HTML tests on generated build output to check for 404 errors, etc
  - htmlproofer ./build --only-4xx --check-html --file-ignore ./build/html/genindex.html,./build/html/search.html,./build/html/index-msg.html --alt-ignore '/.*/' --url-ignore '#'

# after_success and deploy are skipped if build is broken

#after_success:

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_REPO_TOKEN
  local_dir: build/html
  on:
    branch: develop
